In [ ]:
import numpy as np
import tensorflow as tf

In [ ]:
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [ ]:
string1 = tf.Variable('this is a String', tf.string)
number = tf.Variable(123, tf.int16)
floating = tf.Variable(12.5, tf.float16)

In [ ]:
tf.rank(string1) ,tf.rank(number) , tf.rank(floating)   #these are scaler value.. there is no dimension as you can see..

(<tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=0>)

In [ ]:
t1 = tf.Variable([123], tf.int16)
tf.rank(t1)   #here 1 dimension value..

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
#shape of tensor 
t2 = tf.Variable([1,2,3,4], tf.int16)
t3 = tf.Variable([[1,2,3,4],[5,6,7,8]], tf.int16)

t2.shape, t3.shape  #it shows elements in list

(TensorShape([4]), TensorShape([2, 4]))

In [ ]:
t4 = tf.ones([2,2,3])
print(t4)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 2, 3), dtype=float32)


In [ ]:
t4_1 = tf.reshape(t4, [2,3,2])
print(t4_1)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(2, 3, 2), dtype=float32)


In [ ]:
t4_2 = tf.reshape(t4, [3, -1])
print(t4_2)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)
